"""Initial migrate

Revision ID: cba4439b6ad5
Revises: bd1edc0f9e55
Create Date: 2022-02-13 17:38:50.766880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba4439b6ad5'
down_revision = 'bd1edc0f9e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
